<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsRoslynComponent>true</IsRoslynComponent>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" PrivateAssets="all" />
    <PackageReference Include="PolySharp" PrivateAssets="all" IncludeAssets="build; analyzers" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="SR.Designer.cs" DesignTime="True" AutoGen="True" DependentUpon="SR.resx" />
    <EmbeddedResource Update="SR.resx" Generator="ResXFileCodeGenerator" LastGenOutput="SR.Designer.cs" />
    <EmbeddedResource Update="SR.zh-Hans.resx" Generator="ResXFileCodeGenerator" LastGenOutput="SR.Designer.cs" />
  </ItemGroup>

  <PropertyGroup>
    <PolySharpIncludeGeneratedTypes>
      System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute;
    </PolySharpIncludeGeneratedTypes>
  </PropertyGroup>

  <Import Project="..\Ling.FluentValidation.Common\Ling.FluentValidation.Common.projitems" Label="Shared" />

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Ling.FluentValidation.Analyzers.Test</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
