<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IsRoslynComponent>true</IsRoslynComponent>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <!--<CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>-->
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);IDE0028;IDE0057;IDE0130;IDE0290;IDE0301;IDE0305;RCS1085;RS2008</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" PrivateAssets="all" />
    <PackageReference Include="PolySharp" PrivateAssets="all" IncludeAssets="build; analyzers" />
  </ItemGroup>

  <PropertyGroup>
    <PolySharpIncludeGeneratedTypes>
      System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute;
      System.Diagnostics.CodeAnalysis.NotNullWhenAttribute;
      System.Diagnostics.CodeAnalysis.UnscopedRefAttribute;
      System.Runtime.CompilerServices.SkipLocalsInitAttribute;
      System.Runtime.CompilerServices.IsExternalInit;
    </PolySharpIncludeGeneratedTypes>
  </PropertyGroup>

  <Import Project="..\Ling.FluentValidation.Common\Ling.FluentValidation.Common.projitems" Label="Shared" />

</Project>
