<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IsRoslynComponent>true</IsRoslynComponent>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" PrivateAssets="all" />
    <PackageReference Include="PolySharp" PrivateAssets="all" IncludeAssets="build; analyzers" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\SR.Designer.cs" DesignTime="True" AutoGen="True" DependentUpon="SR.resx" />
    <EmbeddedResource Update="Resources\SR.resx" Generator="ResXFileCodeGenerator" LastGenOutput="SR.Designer.cs" />
  </ItemGroup>

  <PropertyGroup>
    <PolySharpIncludeGeneratedTypes>
      System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute;
      System.Runtime.CompilerServices.IsExternalInit;
    </PolySharpIncludeGeneratedTypes>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
    <AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
  </ItemGroup>

  <Import Project="..\Ling.FluentValidation.Common\Ling.FluentValidation.Common.projitems" Label="Shared" />
  
</Project>
