<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\src\Ling.FluentValidation\Ling.FluentValidation.csproj" />
    <ProjectReference Include="..\Ling.FluentValidation.Sample.Contracts\Ling.FluentValidation.Sample.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Ling.FluentValidation.Generators\Ling.FluentValidation.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all" />
  </ItemGroup>

</Project>
